version: "3"
services:
    webserver:
        build: .
        container_name: apache-php
        volumes:
            - ./projects:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - mysql8
    mysql8:
        image: mysql:8
        container_name: mysql8
        volumes:
            - ./database/mysql8:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - "3306:3306"
        restart: always
        
