version: "3"
services:
    webserver:
        build: .
        container_name: apache-php
        volumes:
            - ./projects:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - postgres13
    postgres13:
            image: postgres:13
        container_name: postgres13
        volumes:
            - ./database/postgres13:/var/lib/postgresql
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        restart: always
        
